name: Release Workflow
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print Release Info
        run: |
          echo 'New release created!'
          echo "Version: ${{ github.ref_name }}"